---
title: "PRESS_analysis"
author: "Nicholas Baetge"
date: "12/4/2020"
output: github_document
---

This document provides the analysis and figures for the PRESS manuscript, specifically using data from experiment PN15-3.

# Prepare libraries and data

```{r load libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(lmodel2)
library(blandr)
library(patchwork)
```

```{r load data}
# data <- read_excel("~/GITHUB/PRESS_ms/Input_Data/PRESS_data.xlsx", sheet = "data") %>% 
#   filter(experiment == "PN15-3")

# write_rds(data, "~/GITHUB/PRESS_ms/Input_Data/PRESS_subset.rds")

subset <- read_rds("~/GITHUB/PRESS_ms/Input_Data/PRESS_subset.rds")

glimpse(subset)
```
# Pour v. Pressure TOC

```{r subset data}
toc.data <- subset %>% 
  filter(filter_type == "none", method %in% c("pour", "press", "grav")) %>% 
  drop_na(toc) %>% 
  pivot_wider(id_cols = c(experiment, bottle, timepoint), names_from = method, values_from = c(toc, sd_toc))
```

```{r model 2 regression, echo = FALSE}
reg1 <- lmodel2(toc_press ~ toc_pour, data = toc.data, nperm = 99)
```

```{r model 2 plot, message=FALSE, warning=FALSE}
toc.lm.plot <- toc.data %>% 
  ggplot(aes(x = toc_pour, y = toc_press)) + 
   geom_abline(intercept = reg1$regression.results[3,2],
              slope = reg1$regression.results[3,3],colour = "black", linetype = 2, size = 1) +
   geom_abline(intercept = reg1$confidence.intervals[3,2],
              slope = reg1$confidence.intervals[3,4],colour = "grey", linetype = 3, size = 1) +
  geom_abline(intercept = reg1$confidence.intervals[3,3],
              slope = reg1$confidence.intervals[3,5],colour = "grey", linetype = 3, size = 1) +
  geom_errorbarh(aes(xmin = toc_pour - sd_toc_pour, xmax = toc_pour + sd_toc_pour), height = 0.2) +
  geom_errorbar(aes(ymin = toc_press - sd_toc_press, ymax = toc_press + sd_toc_press), width = 0.2) +
  geom_point(shape = 21, color = "black", fill = "white", size = 3, alpha = 0.8) +
  geom_abline(intercept = 0, slope = 1) +
  labs(x = expression("TOC (Poured), µmol C L"^-1), y = expression("TOC (PRESS), µmol C L"^-1)) +
  xlim(80, 90) +
  ylim(80, 90) +
  annotate( geom = "text", label = expression(atop("y = 1.33x - 28.9", paste("r"^2," = 0.09, ", italic("p "), "= 0.24"))), x = 81, y = 89.5, size = 4) +
  theme_bw(base_size = 16)
  
```

```{r toc blandr}
toc.blandr <- blandr.statistics(toc.data$toc_pour, toc.data$toc_press, sig.level = 0.95)

toc.blandr$bias
```
```{r toc blandr plot, echo = FALSE, warning = FALSE, message = FALSE}
toc.blandr.plot <- toc.data %>% 
  mutate(diff = toc_pour - toc_press,
         mean = (toc_pour + toc_press) / 2) %>% 
  ggplot(., aes(x = mean, y = diff)) +
  geom_hline(yintercept = 0, size = 1, linetype = 1) +
  geom_hline(yintercept = toc.blandr$bias, size = 1, linetype = 2) +
  geom_hline(yintercept = toc.blandr$upperLOA, size = 1, linetype = 3) +
  geom_hline(yintercept = toc.blandr$lowerLOA, size = 1, linetype = 3) +
   geom_point(color = "black", fill = "white",  shape = 21, size = 3, alpha = 0.8) +
  labs(y = expression(italic(paste("Difference, µmol C L"^-1))), x = expression(italic(paste("Mean, µmol C L"^-1)))) +
  theme_bw(base_size = 16) +
  guides(fill = F)
```

```{r combine TOC comparison plots, fig.height=6, fig.width=14, message=FALSE, warning=FALSE}
toc.lm.plot + toc.blandr.plot
```

#Plot TOC and DOC curves

```{r subset and average data}
curve.data <- subset %>%
  select(timepoint:method, toc, doc) %>% 
  group_by(timepoint, filter_type, method) %>%
  mutate(ave_toc = mean(toc, na.rm = T),
         sd_toc = sd(toc, na.rm = T),
         ave_doc = mean(doc, na.rm = T),
         sd_doc = sd(doc, na.rm = T)) %>% 
  ungroup() %>% 
  select(-c(toc,doc)) %>% 
  distinct() %>% 
  mutate(filter_type = ifelse(filter_type == "none", "TOC", "DOC"),
         method = ifelse(method == "pour", "Pour", "PRESS"))

curve.ave.pivot <- curve.data %>% 
  select(-contains("sd")) %>% 
  pivot_longer(c(ave_toc, ave_doc), names_to = "oc", values_to = "ave", names_prefix = "ave_")

curve.sd.pivot <- curve.data %>% 
  select(-contains("ave")) %>% 
  pivot_longer(c(sd_toc, sd_doc), names_to = "oc", values_to = "sd", names_prefix = "sd_")

curve.pivot <- left_join(curve.ave.pivot, curve.sd.pivot) %>% 
  drop_na(sd) %>% 
  mutate(days = hours/24)

```

```{r plot curve, fig.height=6, fig.width=10, message=FALSE, warning=FALSE}
curve.pivot %>% 
  ggplot(aes(x = days, y = ave, group = interaction(filter_type, method))) +
  labs(x = "Days", y = expression("Organic Carbon, µmol C L"^-1), fill = "Method", linetype = "Sample Type") +
  geom_errorbar(aes(ymin = ave - sd, ymax = ave + sd, color = method), width = 0.05, alpha = 0.8) +
  geom_line(aes(color = method, linetype = filter_type), size = 0.75) + 
  geom_point(aes(fill = method), size = 3, shape = 21) +
  scale_color_manual(values = c("Pour" = "#4DAF4A", "PRESS" = "#377EB8")) +
  scale_fill_manual(values = c("Pour" = "#4DAF4A", "PRESS" = "#377EB8")) +
  theme_bw(base_size = 16) +
  guides(color = F)
```


